### ISSUE TITLE
Research Web Crawlers and come up with detailed Crawler Architecture 

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/sleuth#1]
We want the crawler to be able to:
- [ ] Connect to a generic DB (like Postgres) and insert web page info/content info the DB
- [ ] Access web pages and download their content
- [ ] Jump from one page to another
- [ ] Connect to Solar and insert content
- [ ] _Maybe_ process data and connect directly to the DB, or just give raw data straight to the backend
