### ISSUE TITLE
Backend design

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/sleuth#2]
- [ ] Initialize Django project (this will probably be the first commit to our repo)
- [ ] Come up with a few simple use cases for the backend
- [ ] Create high level design for backend service
