### ISSUE TITLE
Front end setup

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/sleuth#3]
- [ ] Come up with a few simple user stories for what the front end should do
- [ ] Initialize front end framework (React) 
- [ ] Research React and create a high level design for how we'll modularize/develop the front end
